sudo: false
language: python

before_install:
  - sudo service redis-server start --bind 127.0.0.1

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
    - env: TOXENV=pep8
      python: 2.7

install:
  pip install tox-travis

script:
  - tox
