sudo: false
language: python

services:
  - redis-server

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
    - env: TOXENV=pep8
      python: 3.5

install:
  pip install tox-travis

script:
  - tox
