[tox]
minversion = 2.0
# avoid sdist
skipsdist = True
envlist = py,pep8

[testenv]
install_command = pip install -c {env:UPPER_CONSTRAINTS_FILE:https://raw.githubusercontent.com/sapcc/requirements/stable/2024.1-m3/upper-constraints.txt} -U {opts} {packages}
setenv = VIRTUAL_ENV={envdir}
         PYTHONWARNINGS=default::DeprecationWarning
         BRANCH_NAME=master
         CLIENT_NAME=rate-limit
         OS_STDOUT_CAPTURE=1
         OS_STDERR_CAPTURE=1
         OS_TEST_TIMEOUT=60
         TESTS_DIR=./rate_limit/tests/
deps = -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt
whitelist_externals = sh
commands = stestr run {posargs}
download = True

[testenv:pep8]
commands = flake8

[testenv:venv]
commands = {posargs}

[flake8]
show-source = True
max-line-length = 140
ignore = D100,D101,D102,D103,D104,D107,D203,D205,E123,E125,E402,E741,W503,W504,W605, H301
builtins = _
exclude=.venv,.git,.tox,dist,doc,*lib/python*,*egg,build


[testenv:docs]
deps = -r{toxinidir}/doc/requirements.txt
commands=
    doc8 doc/source
    python setup.py build_sphinx

[testenv:releasenotes]
commands = sphinx-build -a -E -W -d releasenotes/build/doctrees -b html releasenotes/source releasenotes/build/html

[hacking]
import_exceptions =
    rate_limit.i18n

[doc8]
extensions = .rst, .yaml
# lines should not be longer than 79 characters.
max-line-length = 140
